on:
  workflow_dispatch:
name: upload test
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: mkdir test
      - run: touch test/test1
      - run: touch test/test2
      - run: touch test/test3
      - uses: actions/upload-artifact@v2
        with:
          name: my-test
          path: test/*
